### ISSUE TITLE
Features to add for next release

### ISSUE THREAD

**Issue by jindalk** [morris-lab/newCloneCalling#1]
## Todo for next release
- [ ] Create CellTagR equivalent functions for filtering
- [ ] Write better plotting functions
- [ ] Save intermediate files to pickle
- [ ] Create a streamlined script version with arg parsing for parameters
- [ ] Add more documentation for sparse clone identification
